### PR TITLE
speeding up Quackery

### PR DESCRIPTION
**Pull request by dragoncoder047**
The first thing I noticed when I initially found Quackery was that it was kind of slow to start up.

Back at 7bceed7c6b744c1d5ba7b5cecefa4e9a8d3c0576 the version of Quackery has these times:

```
In [42]: %time !echo -n | python3.6 quackery7bceed7.py >/dev/null
CPU times: user 2.81 ms, sys: 0 ns, total: 2.81 ms
Wall time: 486 ms

In [43]: %time !echo -n | python3.7 quackery7bceed7.py >/dev/null
CPU times: user 2.2 ms, sys: 0 ns, total: 2.2 ms
Wall time: 525 ms

In [44]: %time !echo -n | python3.8 quackery7bceed7.py >/dev/null
CPU times: user 2.18 ms, sys: 0 ns, total: 2.18 ms
Wall time: 329 ms

In [45]: %time !echo -n | python3.9 quackery7bceed7.py >/dev/null
CPU times: user 2.11 ms, sys: 0 ns, total: 2.11 ms
Wall time: 441 ms

In [46]: %time !echo -n | python3.10 quackery7bceed7.py >/dev/null
CPU times: user 2.07 ms, sys: 0 ns, total: 2.07 ms
Wall time: 463 ms

In [47]: %time !echo -n | python3 quackery7bceed7.py >/dev/null
CPU times: user 2.22 ms, sys: 0 ns, total: 2.22 ms
Wall time: 441 ms
```

The latest (a12edfa972ad1a17dcf6cd7baac7c2ce67e4df88):

```
In [51]: %time !echo -n | python3.6 quackery.py >/dev/null
CPU times: user 2.17 ms, sys: 0 ns, total: 2.17 ms
Wall time: 462 ms

In [52]: %time !echo -n | python3.7 quackery.py >/dev/null
CPU times: user 0 ns, sys: 2.68 ms, total: 2.68 ms
Wall time: 462 ms

In [53]: %time !echo -n | python3.8 quackery.py >/dev/null
CPU times: user 0 ns, sys: 2.88 ms, total: 2.88 ms
Wall time: 558 ms

In [54]: %time !echo -n | python3.9 quackery.py >/dev/null
CPU times: user 1.98 ms, sys: 0 ns, total: 1.98 ms
Wall time: 423 ms

In [55]: %time !echo -n | python3.10 quackery.py >/dev/null
CPU times: user 2.27 ms, sys: 0 ns, total: 2.27 ms
Wall time: 426 ms

In [56]: %time !echo -n | python3 quackery.py >/dev/null
CPU times: user 60 µs, sys: 2.25 ms, total: 2.31 ms
Wall time: 425 ms
```

My modifications (as of ed355547f9701120a4b994af0581af6d97faf950) seem to do a little bit to make it start up faster.

```
In [74]: %time !echo -n | python3.6 quackeryFAST.py >/dev/null
CPU times: user 0 ns, sys: 2.13 ms, total: 2.13 ms
Wall time: 442 ms

In [75]: %time !echo -n | python3.7 quackeryFAST.py >/dev/null
CPU times: user 2.12 ms, sys: 0 ns, total: 2.12 ms
Wall time: 628 ms

In [76]: %time !echo -n | python3.8 quackeryFAST.py >/dev/null
CPU times: user 2.16 ms, sys: 84 µs, total: 2.24 ms
Wall time: 305 ms

In [77]: %time !echo -n | python3.9 quackeryFAST.py >/dev/null
CPU times: user 2.1 ms, sys: 81 µs, total: 2.18 ms
Wall time: 405 ms

In [78]: %time !echo -n | python3.10 quackeryFAST.py >/dev/null
CPU times: user 2.08 ms, sys: 80 µs, total: 2.16 ms
Wall time: 409 ms

In [79]: %time !echo -n | python3 quackeryFAST.py >/dev/null
CPU times: user 0 ns, sys: 2.71 ms, total: 2.71 ms
Wall time: 408 ms
```

It seems it's only a few milliseconds though. Do you know anywhere else there could be a bottleneck in Quackery startup?

### CODE REVIEW

**Comment by GordonCharlton** [comment]
Hi,

I'm not sure how startup times could be improved. To be honest, not really a priority for me. I'm more interested in making the python code non-idiomatic and readily understood by someone new to Python.

One thought - it compiles the massive "predefined" string of Quackery every time it starts up. I guess you could pickle that. (Not something I'm familiar with it, but I think pickling is appropriate. Um - chatGPT says that "dill" would be better as it can pickle functions that pickle can't handle. I'm wary of AI generated advice generally, but it might be worth looking into.)

**Comment by dragoncoder047** [comment]
ChatGPT is right in that there is a python package called `dill` that can serialize more complex objects. While the native `pickle` module isn't able to do what you are thinking of (it gives `AttributeError: Can't pickle local object 'quackery.<locals>.python'`, I still think that Quackery should have no dependencies beyond the standard library so that beginners can install Quackery easily (i.e. install python, download quackery.py, run it) versus having to haggle around with pip installing dill as well.

But that's all a moot point because you only need to pickle something if you need to preserve an object between invocations of python, not between function calls. You just need to cache the value in a global variable to save that.

However, there's a subtle problem. I played around with trying to just cache `operators` and `builders` in global variables, but the problem that arose -- and the reason why ChatGPT probably suggested `dill` -- is that the local functions (operators and builders) close over the local variables (work stack, return stack, other local functions, etc.) and so when you invoke `quackery()` again and it loads the cached version, they're still referring to the variables from the first invocation's dead call frame. Here's a demonstration of that:

```
In [19]: _cached = None
    ...: def pared_down_quackery(code):
    ...:     global _cached
    ...:     def some_builtin_function():
    ...:         print("Hello from quackery called with", code)
    ...:     if _cached is None:
    ...:         operators = _cached = {"some_builtin": some_builtin_function}
    ...:     else:
    ...:         operators = _cached.copy()
    ...:     # do something that calls a builtin function
    ...:     operators["some_builtin"]()
    ...: 

In [20]: pared_down_quackery("first invocation")
Hello from quackery called with first invocation

In [21]: pared_down_quackery("second invocation")
Hello from quackery called with first invocation
```


I don't know a lot about what `dill` can do, maybe that is the simplest solution here. Quackery deserves to remain an A+ on [Landon Noll's grading scale](http://www.isthe.com/chongo/tech/comp/c/grading.html).

**Comment by dragoncoder047** [comment]
Sorry for double posting, Github isn't letting me edit my comment now.

```
In [19]: _cached = None
    ...: def pared_down_quackery(code):
    ...:     global _cached
    ...:     def some_builtin_function():
    ...:         print("Hello from quackery called with", code)
    ...:     if _cached is None:
    ...:         operators = _cached = {"some_builtin": some_builtin_function}
    ...:     else:
    ...:         operators = _cached.copy()
    ...:     # do something that calls a builtin function
    ...:     operators["some_builtin"]()
    ...: 

In [20]: pared_down_quackery("first invocation")
Hello from quackery called with first invocation

In [21]: pared_down_quackery("second invocation")
Hello from quackery called with first invocation
```

**Comment by GordonCharlton** [comment]
Thank you for the explanation. I feel better informed now. :-)

And wow! Thank You for the compliment. A+! I feel six feet tall today. :-)

**Comment by dragoncoder047** [comment]
Some progess cloning the dictionary and making the required function swaps:

```
In [8]: def fix(existing, cached):
   ...:     out = copy.deepcopy(cached)
   ...:     mapfix = {cached[k]: existing[k] for k in existing}
   ...:     def process(l):
   ...:         for i, item in enumerate(l):
   ...:             if isinstance(item, list):
   ...:                 process(item)
   ...:             else:
   ...:                 l[i] = mapfix.get(item, item)
   ...:     for k in out:
   ...:         if k in existing:
   ...:             out[k] = mapfix[out[k]]
   ...:         elif isinstance(out[k], list):
   ...:             process(out[k])
   ...:     return out
   ...: 

In [9]: dic = {"foo": fix, "bar": [fix, [fix]]}

In [10]: dic
Out[10]: 
{'foo': <function __main__.fix(existing, cached)>,
 'bar': [<function __main__.fix(existing, cached)>,
  [<function __main__.fix(existing, cached)>]]}

In [13]: dic2 = fix({"foo": lambda: None}, dic)

In [14]: dic2
Out[14]: 
{'foo': <function __main__.<lambda>()>,
 'bar': [<function __main__.<lambda>()>, [<function __main__.<lambda>()>]]}

In [15]: dic2 = fix({"foo": 76}, dic)

In [16]: dic2
Out[16]: {'foo': 76, 'bar': [76, [76]]}
```

**Pull request closed without merging**
