### PR TITLE
Change `backup` and `bailed` to handle protecting stacks.

### LINKED ISSUE #3: `protect` causes `bailed` to mess up `history`
When working on a Quackery extension to solve #1 I needed to create a new protected ancillary stack. Trying to load this extension resulted in an unhelpful problem report:
```Quackery
       Problem: Cannot remove an immovable item.
Quackery Stack: [ file.path share [ ' [ ... ... ... ... ... ... ... ... ... ... ... ] ] join file.path put ' [ [ ... ... ] [ ... ... ] [ ... ... ] ] witheach [ do loadfile ] file.path release ]
  Return stack: {[...] 0} {quackery 1} {[...] 8} {[...] 3} {quackery 0} {build 10} {[...] 2} {releasewords 8} {times 6} {[...] 10} {[...] 1}
```

### What is the problem
The actual problem is caused by the following:
1. `backup` puts one value on the `history` stack for every `protected` ancillary stack.
2. After backing up some stacks can become `protected`, changing the amount of `protected` stacks.
3. `bailed` takes one value from the `history` stack for every `protected` ancillary stack, which may be a different number than was put by `backup` due to new stacks being `protected`.
4. This breaks the structure of the `history` stack causing problems on one of the `bailed`.

This is particularly important because `backup` and `bailed` are run inside `build` which in turn is used to load files, so no new stack can be `protected` by executing `now!` when a file is being loaded.

### How to reproduce
Run code:
```Quackery
[ stack ] is bugged
0 backup protect bugged bailed
```

##### Expected outcome
Quackery stack contains a `0`, no problems arise.

##### Actual outcome
A problem is reported:
```Quackery
       Problem: Cannot remove an immovable item.
Quackery Stack: 
  Return stack: {[...] 0} {quackery 1} {[...] 11} {shell 5} {quackery 1} {[...] 4} {bailed 5} {[...] 6} {times 6} {[...] 10} {[...] 1}
```

### Workaround
Don't `protect` stacks inside the `backup ... bailed` construction.

This is very restrictive because it forbids `protect`ing stacks in any code that is executed at build time, especially inside files loaded with `[ $ 'filename.qky' loadfile ] now!`.

### Solution
One solution I came up with is for `backup` to store the size of the `protected` nest along with sizes of all `protected` stacks so that `bailed` doesn't need to rely on the current size of `protected` to know how many items to consume.

Another solution is that `backup` stores sizes of `protected` stacks in a nest instead of as separate values. I personally prefer this one.

### Sidenote
I think the nest of protected stacks (the first element of the `protected` stack) should include itself. If a stack is protected in a code that should be bailed out of it shouldn't keep being protected and keeping a reference to it only clutters the memory with garbage data.

Sidenote sidenote: what was the logic behind having protected items as a nest inside the `protected` stack instead of just elements of that stack?

### PR DESCRIPTION
**Pull request by olus2000**
Resolves #3.

### Overall thought process
State of the `protected` stack should be saved and what better place to back it up on than the stack that literally exists for this sole purpose: `history`. Along with that change I put all saved stack depths into a nest instead of having them separately on the history stack because this allowed me to have the backed up `protected` state lower on the stack which in turn led to a bit cleaner stack shuffling along the way. Hopefully using `witheach` in `backup` and `bailed` is not a bad practice or a huge loss of efficiency because I believe it makes the code cleaner than other ways of iterating over sequences.

### `backup` changes
Backup now stores following items on the history stack: top item of `protected`, a nest of depths of stacks matching the top item of `protected`, top `n` items from the stack, stack size, nest depth and bail flag. This is a constant amount of 6 items every time so that `bailed` never has to work with variable item amounts.

### `bailed` changes
If the program did not bail `bailed` drops a constant amount of items from the `history` stack. Otherwise it restores everything as it previously did with two differences: it doesn't depend on the current state of `protected` using the nest left on the `history` stack instead, and after all stacks are restored it replaces the top item of `protected` with the old nest of protected stacks.

### `protected` change
This is absolutely unnecessary, but I believe that allowing the programmer to put other nests of nests on the `protected` stack may be useful in some situation, so I added `protected` to protected stacks. This would allow scoped protection of stacks or temporary replacement of the protected stacks altogether, although I can't really explain how that would be useful. I would just like to have such opportunity, and I think it's safe to do so with the new `backup` and `bailed`.

P.S.: Please ignore the werid commit history, this was branched from my own `main` which went through some stuff of its own.

### CODE REVIEW

**Comment by GordonCharlton** [comment]
"Hopefully using witheach in backup and bailed is not a bad practice"

What happens if the user creates a builder that can `bail` within a `times` or `witheach` loop? Using the protected stacks while repairing the protected stacks is a high-risk practice.

**Comment by olus2000** [comment]
Thanks for pointing that out! For some reason it didn't occur to me that loops that drop values from ancillary stacks shouldn't depend on them. It's good to have someone do a reality check on my assumptions.

I'm purposefully trying not to use nest splitting to iterate over them because it makes my brain hurt when I imagine all the new list instances being created along the way. I know that it doesn't really matter and that python handles it efficiently so I won't go out of my way to enforce it, but having other potential implementations in mind I'll try and avoid that way of looping if possible.

**Comment by GordonCharlton** [comment]
No problem! 

Thinking ahead, once the bugs you have found are resolved The Book of Quackery (and TBoQ For Print) will need to be updated to reflect the changes. My preferred solution will be to give you access to the master files. The potential problem here is that the masters are in Apple's .pages format and use fonts I downloaded specifically for the purpose. 

If you are a mac user that is not a problem, but otherwise we will have to consider options. At worst you could send me a list of amendments. At best the online version of Pages at iCloud.com will be usable with custom fonts (I can't test this at the moment as it's currently offline for maintenance.) I looked at another online solution (scanwritr.com) a while ago but it was not usable as it substituted fonts. 

No rush, and I will endeavour to accommodate your preferences when the time comes. :-)

**Comment by olus2000** [comment]
I don't have a mac myself so an online solution would be preferred. If a need arises I can borrow a mac from a friend some evening, but that wouldn't give me as much time to work on it as I would have with my own machine.

**Comment by GordonCharlton** [comment]
I have looked at Apple's online version of Pages and _even on my Mac with the correct fonts installed_ it uses the wrong fonts, and there is no way of fixing that. Unbelievable! 

And, to make it worse, Pages has no way of selecting "all the text written in a specified font" so changing the entire document to a different set of fonts would be more work than I am prepared to do.

[shrug] Oh, well.

I propose that updating The Book of Quackery should be the final step in a bug fix, and I will be your secretary for that task. You send a list of changes, and I will make the changes. I think this is preferable as I am familiar with using Pages, so it will not be difficult for me, and it would be wrong to expect you to borrow a friend's computer and then install fonts on it.

**Comment by olus2000** [comment]
#### In `backup` description in the glossary (page 103)
`backup ( a --> )`
`a` is the number of stack items that backup should copy to the `history` ancillary stack. `backup` records the following information on `history`; **a nest of currently protected ancillary stacks, another nest of their sizes,** copies of `a` stack items, the size of the stack, the size of the return stack, and `false`, to indicate to `bailed` that `bail` has not been invoked.

#### In `bail` description in the glossary (page 103)
*This doesn't regard my changes, I just think it's worth mentioning for the sake of anyone further tinkering with the `history` stack*

`bail ( --> )`
As described in the discussion of Exception Handling above. `bail` replaces the `false` on the top of `history` with `true` to indicate that `bail` has been invoked and causes control flow to move to immediately after the word or nest following the most recently evaluated backup, **consuming the return stack size info from the `history` ancillary stack.**

#### In `bailed` description in the glossary (page 103)
`bailed ( --> a )`
As described in the discussion of Exception Handling above. `bailed` clears the items left on `history` by backup, and restores the stack, **protected ancillary stacks and the list of protected ancillary stacks** to their former state if bail has been invoked. `a` is `true` if bail was invoked and `false` otherwise.

#### In `protected` description in the glossary (page 103)
base temp depth to-do dip.hold b.nesting
times.start times.count times.action **protected**
with.hold mi.tidyup mi.result sort.test

#### In `build` description in the glossary (page 110)
When a problem is detected, either by `build` or by a builder word, compilation is ceased
immediately by `bail` being invoked, resetting any `protect`ed ancillary stacks in use **and the nest in `protected`** to their
state prior to `bailing`.

The rest are changes in the source code according to the diff of `quackery.py`. I think I found all places `bail` related words are mentioned.

I don't know how much effort this requires, but I suggest adding page numbers to chapters in the "Contents" section and to glossary sections in the "Words, Numbers and Nests" chapter. It would make navigating The Book of Quackery much easier.

P.S. I have only just noticed PDF bookmarks which are extremely helpful, but they don't match chapter names and they don't work in some less advanced PDF readers and in the physical copies.

**Pull request closed without merging**
